GilbertHuarcaya/allyn-qhalikay-app

db/migrate/20220131194403_add_colums_to_users.rb

Agregue user_name, dni y address a user

addc olumns to user

---

.gitignore
Gemfile
Gemfile.lock
app/models/user.rb
config/environments/development.rb
config/storage.yml
db/migrate/20220131200238_create_active_storage_tables.active_storage.rb
db/schema.rb

Installing cloudinary

---

app/controllers/medical_histories_controller.rb
app/controllers/records_controller.rb
test/controllers/clinics_controller_test.rb
test/controllers/medical_histories_controller_test.rb
test/controllers/records_controller_test.rb

 records y medical_histroies controllers

---

app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
db/migrate/20220131221800_add_column_to_records.rb

migracion para agregar boolando y obtener medical history filtrado

migracion de record para medical history

---

Gemfile
Gemfile.lock
app/controllers/clinics_controller.rb
app/models/clinic.rb
app/models/record.rb
app/views/clinics/index.html.erb

search terminado en clinics y por aplicar en records

search instalado en gema y aplicado en records y clinics

---

Gemfile
Gemfile.lock
app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_book-card.scss
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_card-trip.scss
app/assets/stylesheets/components/_index.scss
app/controllers/application_controller.rb
app/controllers/clinics_controller.rb
app/javascript/plugins/init_mapbox.js
app/models/clinic.rb
app/models/record.rb
app/policies/application_policy.rb
app/policies/clinic_policy.rb
app/views/clinics/edit.html.erb
app/views/clinics/index.html.erb
app/views/clinics/show.html.erb
test/policies/clinic_policy_test.rb

pundis y pagina index y show de clinics

pundit para evaluar clinicas

---

app/views/layouts/application.html.erb
app/views/records/index.html.erb

acordion item dropdown para cada record

dropdown for each record

---

app/controllers/prescriptions_controller.rb
app/controllers/records_controller.rb
app/views/records/_form.html.erb
app/views/records/edit.html.erb
app/views/records/new.html.erb
app/views/records/show.html.erb
test/controllers/prescriptions_controller_test.rb

Se está modificando las vistas para el edit y create de los records

vistas edit y new Records controller modificada

---

app/views/records/show.html.erb

fixed partial

---

app/controllers/prescriptions_controller.rb
app/views/prescriptions/_form.html.erb
app/views/prescriptions/edit.html.erb
app/views/prescriptions/new.html.erb
app/views/records/show.html.erb

añadimos las vistas y el form del edit y new de prescription

agregamos los formularios de edit y new prescription

---

app/controllers/clinics_controller.rb
app/controllers/records_controller.rb
app/models/user.rb
app/views/clinics/show.html.erb
app/views/medical_images/_form.html.erb
app/views/medical_results/_form.html.erb
app/views/prescriptions/_form.html.erb
app/views/records/_form.html.erb

records ya pueden crear por usuario y clincia

search en form de record

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_card-trip.scss
app/assets/stylesheets/components/_clinic_show.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_home.scss
app/controllers/clinics_controller.rb
app/javascript/plugins/init_mapbox.js
app/javascript/plugins/navbar.js
app/views/clinics/_info_window.html.erb
app/views/clinics/_info_window_user.html.erb
app/views/clinics/show.html.erb
app/views/layouts/application.html.erb
app/views/records/index.html.erb
app/views/shared/_footer.html.erb

navbar foter y show de clinics corregidos y por terminar el navbar y agregar logo de la página

show de clinicas navbar y footer corregidos para ir acorde a la página

---

app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_formclinic.scss
app/assets/stylesheets/components/_formrecord.scss
app/assets/stylesheets/components/_index.scss
app/views/clinics/_form.html.erb
app/views/layouts/application.html.erb
app/views/records/_form.html.erb
app/views/records/new.html.erb
app/views/shared/_footer.html.erb

Formularios de crear clínica y record actualizados

View createclinic

---

app/assets/stylesheets/components/_card-trip.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_home.scss
app/controllers/records_controller.rb
app/models/clinic.rb
app/models/user.rb
app/policies/record_policy.rb
app/views/clinics/_form.html.erb
app/views/clinics/_info_window_user.html.erb
app/views/clinics/index.html.erb
app/views/medical_images/_form.html.erb
app/views/medical_images/_new.html.erb
app/views/medical_results/_form.html.erb
app/views/medical_results/_new.html.erb
app/views/prescriptions/_form.html.erb
app/views/prescriptions/_new.html.erb
app/views/records/_form.html.erb
app/views/records/medical_histories.html.erb
app/views/records/show.html.erb
app/views/shared/_footer.html.erb
app/views/shared/_navbar.html.erb
app/views/shared/_sidebar.html.erb

cambia textos de ingles a español y mejore la pagina de show de los medicos para editar registros
ademas agregue pagina de historial medico y faltaria agregar una página para los médicos para buscar registros por paciente y editar los registros

flujo de usuario casi terminado

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_sesionform.scss
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links.html.erb

Realicé cambios en la vista del login

Login form view

---

app/assets/stylesheets/components/_records.scss
app/views/records/index.html.erb
app/views/records/partials/_medical_images.html.erb
app/views/records/partials/_medical_results.html.erb
app/views/records/partials/_prescriptions.html.erb

se agrego espaciado y color

---

app/assets/stylesheets/components/_records.scss
app/views/pages/home.html.erb

tamaño de imagen usuario home

---

app/assets/stylesheets/components/_sesionform.scss
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb

boton registrarse y login alineados

boton regístrate y signup alineados

---

app/controllers/records_controller.rb
app/policies/record_policy.rb
app/policies/user_policy.rb
app/views/records/patients_records.html.erb
app/views/shared/_navbar.html.erb
config/routes.rb
test/policies/user_policy_test.rb

Búsqueda por dni realizada (patients_records)

búsqueda por id realizada

---

app/assets/stylesheets/components/_records.scss
app/views/records/medical_histories.html.erb
app/views/records/patients_records.html.erb

Se agrego estilos a los records de las vistas de patients_records y medical_histories

estilos en patients record

---

app/controllers/medical_images_controller.rb
app/controllers/medical_results_controller.rb
app/controllers/prescriptions_controller.rb
app/views/records/show.html.erb
config/routes.rb

Hola amigos, los botones de editar y borrar registros y para cada uno de los items están implementados.

editar y borrar registros /historias/recetas/imágenes

---

app/controllers/application_controller.rb
app/controllers/pages_controller.rb
app/policies/application_policy.rb
app/views/pages/create_doctor.html.erb
app/views/records/new.html.erb
app/views/shared/_navbar.html.erb
app/views/shared/_sidebar.html.erb
config/routes.rb

cambiarf rol a medico solo para admin terminado y aplicados cambios al navbar

crear-doctor terminado

---

app/assets/stylesheets/components/_signupform.scss
app/policies/clinic_policy.rb
app/policies/medical_image_policy.rb
app/policies/medical_result_policy.rb
app/policies/prescription_policy.rb
app/policies/record_policy.rb
app/views/clinics/_form.html.erb
app/views/clinics/show.html.erb
app/views/records/_form-new-general.html.erb
app/views/records/_form.html.erb
app/views/records/edit.html.erb
app/views/records/show.html.erb
app/views/shared/_navbar.html.erb
app/views/shared/_sidebar.html.erb

policies terminado y arreglos generales

---

app/assets/stylesheets/components/_button.scss
app/views/records/show.html.erb

se agrego estilos a los botones de detalles, eliminar y editar de la vista del show de records.

estilos a botones de la vista del show de records

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_card-trip.scss
app/assets/stylesheets/components/_formclinic.scss
app/assets/stylesheets/components/_map.scss
app/views/clinics/index.html.erb

map y banner

---

app/views/records/show.html.erb

se agrego una previsualización en miniatura de las imágenes que se suben en el show de record.

se agrego imagen en miniatura de los archivos que se suben a la vista del show de record
